# -*- coding: utf-8 -*-
"""finetune_talkaware

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qstXMOf5WhwDPZzETi7-ng8-xulPvgnJ

# Installations
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install --upgrade --no-cache-dir "unsloth[colab-new]==2026.1.4"

"""# Data pre-processing"""

# caricamento del file per il fine tuning
from datasets import load_dataset
ft_dataset = load_dataset("csv", data_files="toxic_ft.csv")
print(ft_dataset)

ft_dataset = ft_dataset.remove_columns(['testo spagnolo','Violenza', 'Comportamento fisico ', 'Tipo di comportamento  fisico ', 'Comportamento cyber ', 'Tipo di comportamento cyber', 'Comunicazione Aggressiva', 'Tipo di comunicazione aggressiva', 'Classi su singola colonna +  classificazione chatgpt', 'Classi su singola colonna', 'note: tra parentesi è posta la classificazione di ChatGPT quando discordante da quella umana.             Invece, nel campo "spiegazione" tra parentesi è posta la spiegazione fornita da chatGPT sul perché la frase è tossica.'])
print(ft_dataset)

for entry in ft_dataset['train']:
  print(entry)
  break

"""# Fine-tuning"""

import unsloth
from unsloth import FastLanguageModel, PatchDPOTrainer
import torch
from trl import DPOTrainer
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

# caricamento del modello 3B
model_3b, tokenizer_3b = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-3B-Instruct",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

model_3b = FastLanguageModel.get_peft_model(
    model_3b,
    r = 64, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 32,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer_3b,
    chat_template = "llama-3.1",
)

def add_chat(example):
    system = 'Data una frase nel contesto di una conversazione tra partner in una relazione sentimentale, determina se la frase è un esempio di linguaggio tossico o no. In caso affermativo, specifica se la frase rappresenta un caso di cyberviolenza o di violenza di altro tipo e spiegane le motivazioni. Rispondi ESCLUSIVAMENTE in italiano corretto e fluente. Non usare parole in altre lingue.'
    user = example['testo tradotto dallo spagnolo']
    output = ''
    if example['label toxic'] == 0:
        output = 'Questa frase non è tossica.'
    else:
        output = example['Spiegazione']
    messages = [{"role": "system", "content": system}, {"role": "user", "content": user},{"role": "assistant", "content": output}]
    return{"messages": messages}

def format_dataset(examples):
    messages = examples["messages"]
    text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
    return {"text": text}

dataset_tr = ft_dataset['train'].map(add_chat, remove_columns=ft_dataset['train'].column_names)
print(dataset_tr)

dataset_tr = dataset_tr.map(format_dataset, batched=True)
print(dataset_tr)

from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorForSeq2Seq
from unsloth import is_bfloat16_supported
import psutil
import builtins
builtins.psutil = psutil
training_arguments =  TrainingArguments(
        per_device_train_batch_size = 2, # Number of samples per device (GPU) per training step
        gradient_accumulation_steps = 6, # Number of steps to accumulate gradients before updating
        warmup_steps = 5, # Number of steps for learning rate warmup
        num_train_epochs = 5, # Total number of training epochs
        learning_rate = 2e-4, # Initial learning rate for the optimizer
        fp16 = not is_bfloat16_supported(), # Enable FP16 precision if BF16 is not supported
        bf16 = is_bfloat16_supported(), # Enable BF16 precision if supported by hardware
        logging_steps = 1,  # Log training metrics every step
        optim = "adamw_8bit", # Optimizer to use (AdamW with 8-bit precision for memory efficiency)
        weight_decay = 0.01, # Weight decay for regularization to prevent overfitting
        lr_scheduler_type = "linear", # Type of learning rate scheduler (linear decay)
        seed = 3407,
        output_dir = "outputs_ft",
        report_to = "none", # Use this for WandB etc
    )

trainer_3b = SFTTrainer(
    model = model_3b,
    tokenizer = tokenizer,
    train_dataset = dataset_tr,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer),
    dataset_num_proc = 2,
    packing = False,
    args = training_arguments,
)

from unsloth.chat_templates import train_on_responses_only
trainer_3b = train_on_responses_only(
    trainer_3b,
    instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n",
    response_part = "<|start_header_id|>assistant<|end_header_id|>\n\n",
)

trainer_stats_3b = trainer_3b.train()

model_3b.save_pretrained("toxic_ft_model_final_3b")
tokenizer_3b.save_pretrained("toxic_ft_model_final_3b")

"""# DPO Training"""

PatchDPOTrainer()

def add_chat_dpo(example):
    system = 'Data una frase nel contesto di una conversazione tra partner in una relazione sentimentale, determina se la frase è un esempio di linguaggio tossico o no. In caso affermativo, specifica se la frase rappresenta un caso di cyberviolenza o di violenza di altro tipo e spiegane le motivazioni. Rispondi ESCLUSIVAMENTE in italiano corretto e fluente. Non usare parole in altre lingue.'
    user_input = (
        f"Contesto: {example['Contesto']}\n"
        f"Frase: {example['Esempio']}"
    )
    accept_msg = [{"role": "system", "content": system}, {"role": "user", "content": user_input},{"role": "assistant", "content": example['Accept']}]
    reject_msg = [{"role": "system", "content": system}, {"role": "user", "content": user_input},{"role": "assistant", "content": example['Reject']}]
    return {"chosen": accept_msg, "rejected": reject_msg}

def format_dataset_dpo(examples):
    text_chosen = tokenizer_3b.apply_chat_template(examples['chosen'], tokenize=False, add_generation_prompt=False)
    text_rejected = tokenizer_3b.apply_chat_template(examples['rejected'], tokenize=False, add_generation_prompt=False)
    return {"chosen": text_chosen, "rejected": text_rejected}

dpo_org_dataset = load_dataset("csv", data_files="toxic_dpo.csv")
print(dpo_org_dataset)
dpo_org_dataset = dpo_org_dataset['train'].map(add_chat_dpo, remove_columns=dpo_org_dataset['train'].column_names)
print(dpo_org_dataset)
dpo_org_dataset = dpo_org_dataset.map(format_dataset_dpo, batched=True)
print(dpo_org_dataset)

from trl import DPOConfig
train_args= DPOConfig(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_ratio = 0.1,
        num_train_epochs = 7,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 14,
        optim = "adamw_8bit",
        seed = 42,
        report_to = "none",
        lr_scheduler_type = "cosine",
        output_dir = "outputs_dpo"
    )

dpo_trainer_3b = DPOTrainer(
    model = model_3b,
    args = train_args,
    beta = 0.05,
    train_dataset = dpo_org_dataset,
    tokenizer = tokenizer,
    max_length = 1024,
    max_prompt_length = 512,
)
dpo_trainer_3b.train()

model_3b.save_pretrained("toxic_dpo_model_final_3b")
tokenizer_3b.save_pretrained("toxic_dpo_model_final_3b")

from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get('HF_TOKEN')
login(hf_token)

model_3b.push_to_hub("alefiniguerra01/toxic_dpo_model_final_3b")
tokenizer_3b.push_to_hub("alefiniguerra01/toxic_dpo_model_final_3b")