# -*- coding: utf-8 -*-
"""interfaccia_talkaware

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tjsx-Fxz9LvqT6FmrpkMbMyVaOvgbZvF

# Installations
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install --upgrade --no-cache-dir "unsloth[colab-new]==2026.1.4"

"""# Model loading and Data Handling"""

from google.colab import userdata
from huggingface_hub import login

hf_token = userdata.get('HF_TOKEN')
login(hf_token)
model_3b_path = "alefiniguerra01/toxic_dpo_model_final_3b"

import torch
import unsloth
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template
from transformers import TextStreamer

max_seq_length = 2048 # Maximum sequence length for model inputs
dtype = None # Data type for model weights (None for auto-detection)
load_in_4bit = True # Enables 4-bit quantization for reduced memory usage

if torch.cuda.is_available():
  device = torch.device("cuda")
if not torch.cuda.is_available() and load_in_4bit:
    raise RuntimeError("Quantizzazione 4-bit richiede CUDA. Disabilita 'load_in_4bit' o usa una GPU.")

try:
  model_3b, tokenizer_3b = FastLanguageModel.from_pretrained(
      model_name = model_3b_path,
      max_seq_length = max_seq_length,
      dtype = dtype,
      load_in_4bit = load_in_4bit,
  )

  tokenizer = get_chat_template(
        tokenizer_3b,
        chat_template = "llama-3.1",
  )
  tokenizer.pad_token = tokenizer.eos_token
  tokenizer.padding_side = "right"
  FastLanguageModel.for_inference(model_3b)

  def infer_with_3b(inputs):

    with torch.no_grad():
      attention_mask = (inputs != tokenizer.pad_token_id).long().to(device)

      # Generate output tokens from the model
      outputs_3b = model_3b.generate(
          input_ids = inputs,
          attention_mask=attention_mask,
          max_new_tokens = 512, # Maximum number of tokens to generate
          use_cache = True # Enables caching for faster generation
      )

    # Decode the generated tokens to a string
    decoded_output = tokenizer.batch_decode(outputs_3b, skip_special_tokens=False)[0]

    # Tokens marking the start and end of the assistant's response
    start_token = "<|start_header_id|>assistant<|end_header_id|>"
    end_token = "<|eot_id|>"

    start_index = decoded_output.find(start_token)
    end_index = decoded_output.find(end_token, start_index)

    if start_index != -1:
      start_index += len(start_token)
      if end_index != -1:
        answer = decoded_output[start_index:end_index].strip() # se vengono
        return answer
      answer = decoded_output[start_index:].strip()
      return answer + "\n\n[Nota: La risposta potrebbe essere stata troncata.]"
    else:
      return decoded_output.strip() + "\n\n[Nota: I marker di estrazione non sono stati trovati.]"
except Exception as e:
    print(f"Errore durante il caricamento del modello Unsloth: {e}")
    print("Assicurati che 'model_3b_path' sia corretto e che l'ambiente sia configurato per Unsloth/CUDA.")

import csv

# File paths for storing user feedback related to each model
data_file_3b = "user_feedback_3b.csv"

try:
  with open(data_file_3b, mode="a", newline="") as file:
    writer = csv.writer(file)
    if file.tell() == 0:
      writer.writerow(["timestamp", "user_context", "user_sentence", "model_explanation", "choice", "new_explanation"])
except Exception as e:
    print(f"Errore durante l'apertura/creazione del file CSV: {e}")

"""# User Interface Design"""

import gradio as gr
from datetime import datetime
import time

# System prompt for the conversation
system = (
    "Data una frase nel contesto di una conversazione tra partner in una relazione sentimentale, determina se la frase è un esempio di linguaggio tossico o no. In caso affermativo, specifica se la frase rappresenta un caso di cyberviolenza o di violenza di altro tipo e spiegane le motivazioni. Rispondi ESCLUSIVAMENTE in italiano corretto e fluente. Non usare parole in altre lingue."
)

# Processes the user's sentence and returns the assistant's response.

def process_sentence(context, sentence):
  user_input = (
      f"Contesto: {context}\n"
      f"Frase: {sentence}"
  )

  # Construct the conversation messages
  messages = [
      {"role": "system", "content": system},
      {"role": "user", "content": user_input}
  ]
  # Tokenize and prepare the input tensors using the chat template
  inputs = tokenizer.apply_chat_template(
      messages,
      tokenize = True,
      add_generation_prompt = True,
      return_tensors = "pt",
  ).to(device)

  result = infer_with_3b(inputs)
  return result.strip()

"""# Gradio interface components"""

import random
import time
from bs4 import BeautifulSoup
import concurrent.futures
already_saved_feedback = False

initial_message = [
    {"role": "assistant", "content": "Ciao! Sono TalkAware e sono qui per aiutarti.\n\nIl mio scopo è quello di analizzare una frase e di predire se il testo contiene elementi di violenza informatica tra partner.\n\nSpiegami innanzitutto il contesto in cui ti è stata detta la frase da analizzare."}
]

def initialize_chat():
    history = []
    yield (
            history,
            history,
            gr.update(visible=False),
            gr.update(visible=False),
            gr.update(visible=True)
    )
    time.sleep(1)

    history += initial_message
    yield (
            history,
            history,
            gr.update(visible=False),
            gr.update(visible=False),
            gr.update(visible=True)
    )

# funzione risposta del sistema
def chatbot_response(message, history):

    if not history:
        history = []

    if "non ho capito" in message.lower() or "faq" in message.lower() or "ripeti" in message.lower():
        history.append({"role": "user", "content": message})
        history.append({"role": "assistant", "content": ""})
        time.sleep(0.5)
        for i in range(1, 4):
            dots = "●" * i
            history[-1]["content"] = dots
            yield history, "", gr.update(interactive = False), gr.update(visible=False), user_context
            time.sleep(0.6)

        response = (
            "Certo, ripeto subito!\n\nIl mio scopo è quello di analizzare un testo e di predire se il testo contiene elementi di violenza informatica tra partner.\n\nSpiegami innanzitutto il contesto in cui ti è stata detta la frase da analizzare."
        )
        history[-1]["content"] = response
        yield history, "", gr.update(interactive = True), gr.update(visible=False), user_context

    else:
        user_context = message
        history.append({"role": "user", "content": user_context, "meta": "context"})
        history.append({"role": "assistant", "content": ""})

        time.sleep(0.5)
        for i in range(1, 4):
            dots = "●" * i
            history[-1]["content"] = dots
            yield history, "", gr.update(visible = False), gr.update(visible=False), user_context
            time.sleep(0.6)

        sentence_request = "Digita ora la frase che ti è stata detta oppure descrivimi una situazione che ritieni potenzialmente tossica."
        history[-1]["content"] = sentence_request
        yield history, "", gr.update(visible=False), gr.update(visible=True), user_context

def chatbot_analysis(message, history, user_context, model_explanation):
  global already_saved_feedback
  already_saved_feedback = False

  if "non ho capito" in message.lower() or "faq" in message.lower() or "ripeti" in message.lower():
        history.append({"role": "user", "content": message})
        history.append({"role": "assistant", "content": ""})
        time.sleep(0.5)
        for i in range(1, 4):
            dots = "●" * i
            history[-1]["content"] = dots
            yield history, "", gr.update(interactive = False), gr.update(visible=False), user_context, user_sentence, model_explanation
            time.sleep(0.6)

        response = (
            "Certo, ripeto subito!\n\nIl mio scopo è quello di analizzare un testo e di predire se il testo contiene elementi di violenza informatica tra partner.\n\nTi chiedo di spiegarmi innanzitutto il contesto in cui è stata pronunciata la frase che ritieni potenzialmente tossica e, successivamente, ti chiederò ciò che ti è stato detto. Io analizzerò il contenuto e ti darò un parere."
        )
        history[-1]["content"] = response
        yield history, "", gr.update(interactive = True), gr.update(visible=False), user_context, user_sentence, model_explanation

  else:
      user_sentence = message
      history.append({"role": "user", "content": user_sentence, "meta": "sentence"})
      history.append({"role": "assistant", "content": ""})

      time.sleep(1.5)

      with concurrent.futures.ThreadPoolExecutor() as executor:
                future = executor.submit(process_sentence, user_context, user_sentence)

                i = 1
                while not future.done():
                    dots = "." * ((i % 3) + 1)
                    history[-1]["content"] = f"Sto analizzando{dots}"
                    yield history, "", gr.update(visible=False), gr.update(visible=False), user_context, user_sentence, model_explanation
                    time.sleep(0.6)
                    i += 1

                try:
                    analysis_response = future.result(timeout=0)
                except Exception as e:
                    analysis_response = "C'è stato un errore nell'elaborazione. Riprova più tardi."
                    print("Errore:", e)

  history[-1]["content"] = analysis_response
  model_explanation = analysis_response
  yield history, "", gr.update(visible=False), gr.update(visible=False), user_context, user_sentence, model_explanation

  # Feedback
  time.sleep(3)
  feedback_message = "📣 Adesso ti chiederò un feedback per migliorare le mie analisi future..."
  history.append({"role": "assistant", "content": ""})
  for i in range(1, 4):
            dots = "●" * i
            history[-1]["content"] = dots
            yield history, "", gr.update(visible=False), gr.update(visible=False), user_context, user_sentence, model_explanation
            time.sleep(0.6)

  history[-1]["content"] = feedback_message
  yield history, "", gr.update(visible = False), gr.update(visible=True), user_context, user_sentence, model_explanation

# verifica che la scelta dell'utente sia Sì o No
def control_choice(history, user_choice):
  if user_choice not in ["👍 Sì", "👎 No"]:
    for msg in reversed(history):
      if msg["role"] == "user" and "choice" in msg["meta"]:
        user_choice = msg["content"]
      break
  return user_choice

# salva il feedback sul file csv
def save_feedback(timestamp, user_context, user_sentence, model_explanation, user_choice, new_explanation):
  global already_saved_feedback
  data_file = data_file_3b

  if already_saved_feedback:
    return

  try:
      with open(data_file, mode="a", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow([timestamp, user_context, user_sentence, model_explanation, user_choice, new_explanation])
        already_saved_feedback = True
  except Exception as e:
        print("[ERRORE] Impossibile scrivere nel file CSV:", e)

# funzione che decide cosa fare in base al feedback dell'utente
def feedback_choice_handler(history, user_choice, user_context, user_sentence, model_explanation):
  timestamp = datetime.now().isoformat()
  data_file = data_file_3b

  if user_choice == "👍 Sì":
    response = "Grazie per il tuo feedback!\n\nHai ancora bisogno del mio aiuto?"
    history[-1]["content"] = response
    yield history, gr.update(visible=False), gr.update(visible=False), gr.update(value = "-", visible = False), gr.update(visible = False), gr.update(visible = True)

    # save feedback to csv
    save_feedback(timestamp, user_context, user_sentence, model_explanation, "yes", "Spiegazione corretta")

  elif user_choice == "👎 No":
    response = "Mi dispiace..\n\nFornisci una nuova spiegazione per migliorare le mie analisi."
    history[-1]["content"] = response
    yield history, gr.update(visible=False), gr.update(visible=False), gr.update(value = "-", visible = False), gr.update(visible = True), gr.update(visible = False)

# funzione che recupera il feedback dell'utente
def feedback_handler(feedback_choice, history, user_context, user_sentence, model_explanation):
    history.append({"role": "user", "content": feedback_choice, "meta": "choice"})

    choice = control_choice(history, feedback_choice)
    if choice == "-":
      history.pop()
      yield history, gr.update(visible=False), gr.update(visible=False), gr.update(value = "-", visible=False), gr.update(visible = False), gr.update(visible = False)

    else:
      yield history, gr.update(visible=False), gr.update(visible=False), gr.update(value = "-", visible=False), gr.update(visible = False), gr.update(visible = False)

      new_explanation = gr.State("")
      time.sleep(0.8)
      history.append({"role": "assistant", "content": ""})
      for i in range(1, 4):
        dots = "●" * i
        history[-1]["content"] = dots
        yield history, gr.update(visible=False), gr.update(visible=False), gr.update(value = "-", visible=False), gr.update(visible = False), gr.update(visible = False)
        time.sleep(0.6)

    for msg in reversed(history):
      if msg["role"] == "user" and "choice" in msg["meta"]:
        user_choice = msg["content"]
        break

    yield from feedback_choice_handler(history, user_choice, user_context, user_sentence, model_explanation)

# funzione che prende in input la nuova spiegazione dell'utente (se quella del modello è errata)
def new_explanation_handler(new_explanation, history, user_context, user_sentence, model_explanation):
  timestamp = datetime.now().isoformat()

  history.append({"role": "user", "content": new_explanation})
  yield history, gr.update(visible= False), gr.update(value="", visible = False), gr.update(visible = False)

  time.sleep(0.8)
  history.append({"role": "assistant", "content": ""})
  confirm_message = "Grazie! La tua risposta è stata salvata!\n\nHai ancora bisogno del mio aiuto?"
  for i in range(1, 4):
      dots = "●" * i
      history[-1]["content"] = dots
      yield history, gr.update(visible= False), gr.update(value="", visible = False), gr.update(visible = False)
      time.sleep(0.6)
  history[-1]["content"] = confirm_message
  yield history, gr.update(visible=False), gr.update(value="", visible=False), gr.update(visible = True)

  # Save feedback to CSV
  save_feedback(timestamp, user_context, user_sentence, model_explanation, "no", new_explanation)

# funzione che decide cosa fare sulla base della scelta dell'utente (nuova richiesta o meno)
def request_choice_handler(history, user_choice):
  if user_choice == "👍 Sì":
    sentence = "Inserisci un nuovo contesto in cui ti è stata detta una frase potenzialmente tossica."
    history[-1]["content"] = sentence
    yield history, gr.update(visible=True), gr.update(value = "-", visible=False)

  elif user_choice == "👎 No":
    sentence = "Arrivederci!"
    history[-1]["content"] = sentence
    yield history, gr.update(visible=False), gr.update(value = "-", visible=False)

# funzione che riceve la scelta dell'utente sull'avere o no una nuova richiesta
def request_handler(request_choice, history):
  history.append({"role": "user", "content": request_choice, "meta": "choice"})

  choice = control_choice(history, request_choice)
  if choice == "-":
    history.pop()
    yield history, gr.update(visible=False), gr.update(value = "-", visible=False)

  else:
    yield history, gr.update(visible=False), gr.update(value = "-", visible=False)

    time.sleep(0.8)
    history.append({"role": "assistant", "content": ""})
    for i in range(1, 4):
          dots = "●" * i
          history[-1]["content"] = dots
          yield history, gr.update(visible=False), gr.update(value = "-", visible=False)
          time.sleep(0.6)

  for msg in reversed(history):
      if msg["role"] == "user" and "choice" in msg["meta"]:
        user_choice = msg["content"]
        break

  yield from request_choice_handler(history, user_choice)

from huggingface_hub import hf_hub_download

repo_id = "alefiniguerra01/web_assets"

css_path = hf_hub_download(repo_id=repo_id, filename="style_css.css")
html_path = hf_hub_download(repo_id=repo_id, filename="style_html.html")

print("CSS salvato in:", css_path)
print("HTML salvato in:", html_path)


# caricamento file CSS
try:
  with open(css_path, "r", encoding = "utf-8") as file_css:
    my_css = file_css.read()
except FileNotFoundError:
  my_css = ""
  print(f"Avviso: File CSS non trovato. L'applicazione potrebbe non essere stilizzata correttamente.")
except Exception as e:
  my_css = ""
  print(f"Errore durante la lettura del file CSS: {e}.")

# caricamento file HTML
def get_html_content_from_file(file_path, element_id=None):
    try:
      with open(file_path, 'r', encoding='utf-8') as f:
        html_doc = f.read()
    except FileNotFoundError:
        return f"Errore: File non trovato al percorso: {file_path}"
    except Exception as e:
        return f"Errore durante la lettura del file HTML: {e}"

    soup = BeautifulSoup(html_doc, 'html.parser')

    target_element = None
    if element_id:
      target_element = soup.find(id=element_id)

    if target_element:
      return str(target_element)
    else:
      return f"Elemento HTML non trovato con ID='{element_id}' nel file."

html_title = get_html_content_from_file(html_path, element_id="title")
html_description = get_html_content_from_file(html_path, element_id="description")

with gr.Blocks(theme = gr.themes.Soft(), css= my_css) as demo:

  title = gr.HTML(html_title)
  description = gr.HTML(html_description)

  gr.Markdown()

  start_button = gr.Button("AVVIA", elem_classes = "start_button")

  chat_container = gr.Column(visible=False)
  with chat_container:
    chatbot = gr.Chatbot(value=[], label = "TalkAware", type="messages", layout="bubble", elem_classes = "chatbot")

    textbox_context = gr.Textbox(
        placeholder="Es. Il mio ragazzo vuole decidere sempre cosa devo indossare",
        interactive=True,
        show_label = False,
        elem_classes="textbox"
    )

    textbox_sentence = gr.Textbox(
        placeholder="Es. Dovresti vestirti in modo meno provocante",
        interactive=True,
        visible = False,
        show_label = False,
        elem_classes = "textbox"
    )

    new_explanation = gr.Textbox(
        placeholder = "Inserisci la nuova spiegazione...",
        interactive = True,
        visible = False,
        show_label = False,
        elem_classes = "textbox"
    )

    feedback_radio = gr.Radio(
        choices = ["👍 Sì", "👎 No", "-"],
        value = "-",
        label = "La spiegazione che ti ho fornito è corretta?",
        visible = False,
        interactive = True,
        elem_classes = "radio_button"
    )

    analysis_request = gr.Radio(
        choices = ["👍 Sì", "👎 No", "-"],
        value = "-",
        label = "Vuoi eseguire un'altra analisi?",
        visible = False,
        interactive = True,
        elem_classes = "radio_button"
    )
    state = gr.State([])

    user_context = gr.State("")
    user_sentence = gr.State("")
    model_explanation = gr.State("")

    textbox_context.submit(chatbot_response, [textbox_context, state], [chatbot, textbox_context, textbox_context, textbox_sentence, user_context])

    textbox_sentence.submit(chatbot_analysis, [textbox_sentence, state, user_context, model_explanation], [chatbot, textbox_sentence, textbox_sentence, feedback_radio, user_context, user_sentence, model_explanation], show_progress="minimal").then(lambda h: h, [chatbot], [state])

    feedback_radio.change(feedback_handler, [feedback_radio, state, user_context, user_sentence, model_explanation], [chatbot, user_context, user_sentence, feedback_radio, new_explanation, analysis_request])

    new_explanation.submit(new_explanation_handler, [new_explanation, state, user_context, user_sentence, model_explanation], [chatbot, user_context, new_explanation, analysis_request])

    analysis_request.change(request_handler, [analysis_request, state], [chatbot, textbox_context, analysis_request])

  start_button.click(
      initialize_chat,
      None,
      [chatbot, state, start_button, description, chat_container]
  )

"""# Launch"""

demo.launch()